services:
  # api:
  #   build: .
  #   container_name: grmx-api
  #   ports:
  #     - 8800:8800
  #   command: "npm start"

  grmx-mongodb:
    container_name: grmx-mongodb
    image: mongo
    restart: always
    command: "mongod --port 27020"
    ports:
      - "27020:27020"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data:/data/db

  grmx-mongo-express:
    container_name: grmx-mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@grmx-mongodb:27020/
      ME_CONFIG_BASICAUTH: false
